Feature/#11 avro nested data support
exasol/import-export-udf-common-scala pull request #12
Opened 2020-10-26 14:22 UTC by morazow

Fixes #11.
Fixes #5.

2020-10-27 14:15 UTC, AnastasiiaSergienko requested changes
Just a few small comments

2020-10-28 08:24 UTC, morazow commented on src/main/scala/com/exasol/avro/AvroRow.scala
>              "Avro Union type should contain a primitive and null!"
Yes, union are represented as array of two, where one of them is null.
But it is about the union type so, `a primitive and null types` would be better.

2020-10-28 08:46 UTC, morazow commented on src/main/scala/com/exasol/avro/AvroRow.scala
> +      }
Done

2020-10-28 09:09 UTC, AnastasiiaSergienko approved these changes
:+1:

2020-10-28 09:44 UTC, merged